import TopNavbar from '@/components/TopNavbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<TopNavbar />
				<main className='p-10 md:pl-[4rem]'> {children}</main>
			</body>
		</html>
	)
}
